# Generated by Django 4.2.15 on 2024-08-14 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fruitipedia.fruits.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.MinLengthValidator(2),
                            fruitipedia.fruits.validators.FruitNameValidator(
                                message="Fruit name should contain only letters!"
                            ),
                        ],
                    ),
                ),
                ("image", models.URLField()),
                ("description", models.TextField()),
                ("nutrition", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruits",
                        to="fruits.category",
                    ),
                ),
            ],
        ),
    ]
